- role: "Reviewer"
  organization: "Materials (Journal, ISSN 1996-1944)"
  date: "Ongoing"
  description: "Served as a peer reviewer for the open-access academic journal 'Materials'."
- role: "Workshop Organizer"
  organization: "2024 AMS-CDT Conference"
  date: "2024"
  description: "Organized and ran a workshop session at the conference."
- role: "Committee Member"
  organization: "I-Form Data Management Committee"
  date: "Ongoing"
  description: "Primary contributor driving the adoption of data transparency and hosted data repositories. Primary developer and maintainer for deploying openly available data repository platforms."
- role: "Committee Member"
  organization: "I-Form Equity, Diversity, and Inclusion (EDI) Committee"
  date: "Ongoing"
  description: "Partnered with the Irish Centre for Diversity to foster an inclusive and equitable research culture within the institute."
- role: "EPE Contributor"
  organization: "I-Form Research Centre"
  date: "Ongoing"
  description: "Active participant in judging and providing technical support for Education and Public Engagement (EPE) efforts. Developing new EPEs including AI-assisted design 3D printing workshops in collaboration with local community centres."
